const SUPABASE_URL='https://zbogfymmlnifzoasemlt.supabase.co';
const SUPABASE_KEY='sb_publishable_77b2DtF2XQLyfKEg7ZBNYA_odCDFWVJ';
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let currentUser=null,currentProfile=null,toastTimer=null;

const $=id=>document.getElementById(id);
function escapeHtml(text=''){const div=document.createElement('div');div.textContent=text;return div.innerHTML}
function getInitials(name=''){const p=name.trim().split(/\s+/).filter(Boolean);if(!p.length)return'?';return(p.length===1?p[0][0]:p[0][0]+p[p.length-1][0]).toUpperCase()}
function formatDate(value){return new Date(value).toLocaleString()}
function formatMemberSince(value){return new Date(value).toLocaleDateString(undefined,{month:'short',year:'numeric'})}
function setAuthMessage(message,isError=false){$('authMessage').textContent=message;$('authMessage').classList.toggle('error',isError)}
function setComposerMessage(message,isError=false){$('composerMessage').textContent=message;$('composerMessage').classList.toggle('error',isError)}
function showToast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600)}
function showLogin(){$('loginForm').style.display='block';$('signupForm').style.display='none';$('loginTab').classList.add('active');$('signupTab').classList.remove('active');setAuthMessage('')}
function showSignup(){$('loginForm').style.display='none';$('signupForm').style.display='block';$('loginTab').classList.remove('active');$('signupTab').classList.add('active');setAuthMessage('')}
function getUserName(user){if(!user)return'Community Member';if(currentProfile?.full_name)return currentProfile.full_name.trim();const m=user.user_metadata||{};return m.full_name||m.name||user.email?.split('@')[0]||'Community Member'}
function clearMemberParam(){const url=new URL(location.href);if(url.searchParams.has('member')){url.searchParams.delete('member');history.replaceState({},'',url)}}

async function signUp(){const name=$('signupName').value.trim(),email=$('signupEmail').value.trim(),password=$('signupPassword').value,button=$('signupButton');if(!name)return setAuthMessage('Please enter your full name.',true);if(!email)return setAuthMessage('Please enter your email address.',true);if(password.length<6)return setAuthMessage('Your password must be at least 6 characters.',true);button.disabled=true;button.textContent='Creating Account...';const{data,error}=await supabaseClient.auth.signUp({email,password,options:{data:{full_name:name}}});button.disabled=false;button.textContent='Create Account';if(error)return setAuthMessage(error.message,true);setAuthMessage(data.user&&!data.session?'Account created. Please check your email and confirm your address before signing in.':'Account created successfully.')}
async function signIn(){const email=$('loginEmail').value.trim(),password=$('loginPassword').value,button=$('loginButton');if(!email||!password)return setAuthMessage('Enter your email and password.',true);button.disabled=true;button.textContent='Signing In...';const{data,error}=await supabaseClient.auth.signInWithPassword({email,password});button.disabled=false;button.textContent='Sign In';if(error)return setAuthMessage(error.message,true);if(data.user)await handleUserSession(data.user)}
async function signOut(){if(currentUser)localStorage.removeItem(profileDraftKey(currentUser.id));const{error}=await supabaseClient.auth.signOut();if(error)return alert(error.message);currentUser=null;currentProfile=null;closeMyProfile();$('memberProfileModal').classList.remove('open');clearMemberParam();updateAuthUI(null)}
async function loadCurrentProfile(user){currentProfile=null;if(!user)return;const{data,error}=await supabaseClient.from('profiles').select('id, full_name, bio, created_at').eq('id',user.id).maybeSingle();if(!error)currentProfile=data||null}
async function handleUserSession(user){currentUser=user;await loadCurrentProfile(user);updateAuthUI(user);await loadPosts();await openRequestedMemberProfile()}
async function initializeAuth(){const{data}=await supabaseClient.auth.getSession();currentUser=data.session?.user||null;await loadCurrentProfile(currentUser);updateAuthUI(currentUser)}
supabaseClient.auth.onAuthStateChange(async(_,session)=>{currentUser=session?.user||null;await loadCurrentProfile(currentUser);updateAuthUI(currentUser);if(currentUser){await loadPosts();await openRequestedMemberProfile()}else{clearMemberParam()}});

function updateAuthUI(user){$('guestShell').style.display=user?'none':'grid';$('memberShell').style.display=user?'block':'none';$('accountWrap').style.display=user?'block':'none';if(user){const name=getUserName(user);$('accountName').textContent=name;$('accountAvatar').textContent=getInitials(name);$('composerAvatar').textContent=getInitials(name);$('memberWelcomeTitle').textContent=`Welcome back, ${name.split(' ')[0]}`;}else{$('posts').innerHTML='';$('accountMenu').classList.remove('open')}}
function toggleAccountMenu(){$('accountMenu').classList.toggle('open')}
document.addEventListener('click',e=>{if(!e.target.closest('.account-wrap'))$('accountMenu')?.classList.remove('open')});

function profileDraftKey(id){return`nlc-profile-draft-${id}`}
function getProfileDraft(){if(!currentUser)return null;try{return JSON.parse(localStorage.getItem(profileDraftKey(currentUser.id))||'null')}catch{return null}}
function saveProfileDraft(){if(!currentUser)return;localStorage.setItem(profileDraftKey(currentUser.id),JSON.stringify({full_name:$('editProfileName').value,bio:$('editProfileBio').value}))}
function openMyProfile(){if(!currentUser)return;$('accountMenu').classList.remove('open');const draft=getProfileDraft();$('editProfileEmail').value=currentUser?.email||'';$('editProfileName').value=draft?.full_name??currentProfile?.full_name??getUserName(currentUser);$('editProfileBio').value=draft?.bio??currentProfile?.bio??'';$('editProfileMessage').textContent='';$('editProfileModal').classList.add('open')}
function closeMyProfile(){$('editProfileModal').classList.remove('open')}
async function saveProfile(){if(!currentUser)return;const name=$('editProfileName').value.trim(),bio=$('editProfileBio').value.trim(),button=$('saveProfileButton');if(!name){$('editProfileMessage').textContent='Please enter your full name.';return}button.disabled=true;button.textContent='Saving...';const{data,error}=await supabaseClient.from('profiles').update({full_name:name,bio:bio||null,updated_at:new Date().toISOString()}).eq('id',currentUser.id).select('id, full_name, bio, created_at').single();button.disabled=false;button.textContent='Save Changes';if(error){$('editProfileMessage').textContent=error.message;return}currentProfile=data;localStorage.removeItem(profileDraftKey(currentUser.id));updateAuthUI(currentUser);closeMyProfile();showToast('✓ Changes saved');await loadPosts()}

async function createPost(){if(!currentUser)return;const textarea=$('postContent'),button=$('postButton'),content=textarea.value.trim();if(!content)return setComposerMessage('Write something first.',true);button.disabled=true;setComposerMessage('Posting...');const{error}=await supabaseClient.from('posts').insert([{content,author_name:getUserName(currentUser),user_id:currentUser.id}]);button.disabled=false;if(error)return setComposerMessage(error.message,true);textarea.value='';setComposerMessage('');showToast('Post published');await loadPosts()}

async function loadPosts(){if(!currentUser){$('posts').innerHTML='';return}const container=$('posts');container.innerHTML='<div class="empty-state">Loading conversations...</div>';const{data,error}=await supabaseClient.from('posts').select('*').order('created_at',{ascending:false});if(error){container.innerHTML='<div class="empty-state">Unable to load posts.</div>';return}if(!data?.length){container.innerHTML='<div class="empty-state">No posts yet. Start the first conversation.</div>';return}container.innerHTML=data.map(renderPost).join('');for(const post of data){loadLikeCount(post.id);loadComments(post.id)}await refreshLikeStates()}
function authorButton(name,userId,cls='author-name-button'){return userId?`<button class="${cls}" type="button" onclick="openMemberProfile('${userId}')">${escapeHtml(name)}</button>`:`<span class="${cls.replace('-button','')}">${escapeHtml(name)}</span>`}
function renderPost(post){const name=post.author_name||'Community Member',initials=getInitials(name);return`<article class="post"><div class="post-author"><div class="avatar">${escapeHtml(initials)}</div><div class="author-meta">${authorButton(name,post.user_id)}<div class="post-date">${formatDate(post.created_at)}</div></div></div><div class="post-content">${escapeHtml(post.content)}</div><div class="post-actions"><button class="action-button like-button" id="like-button-${post.id}" type="button" onclick="likePost('${post.id}')">♡ Like <span id="like-count-${post.id}">0</span></button></div><div class="comments"><div class="comments-title" id="comments-title-${post.id}">Comments</div><div id="comments-${post.id}">Loading comments...</div><div class="comment-box"><input id="comment-${post.id}" maxlength="500" placeholder="Write a comment..." onkeydown="handleCommentKey(event,'${post.id}')"><button class="primary comment-button" data-post-id="${post.id}" type="button">Comment</button></div></div></article>`}

async function loadComments(postId){if(!currentUser)return;const box=$(`comments-${postId}`);if(!box)return;const{data,error}=await supabaseClient.from('comments').select('*').eq('post_id',postId).order('created_at',{ascending:true});if(error){box.innerHTML='<div class="muted">Unable to load comments.</div>';return}const count=data?.length||0;$(`comments-title-${postId}`).textContent=`💬 ${count} Comment${count===1?'':'s'}`;if(!count){box.innerHTML='<div class="muted">No comments yet.</div>';return}box.innerHTML=data.map(c=>{const name=c.author_name||'Community Member';return`<div class="comment"><div class="comment-head"><div class="avatar">${escapeHtml(getInitials(name))}</div>${authorButton(name,c.user_id,'author-name-button comment-author')}</div><div class="comment-content">${escapeHtml(c.content)}</div><div class="comment-date">${formatDate(c.created_at)}</div></div>`}).join('')}
async function createComment(postId){if(!currentUser)return;const input=$(`comment-${postId}`),button=document.querySelector(`[data-post-id="${postId}"]`),content=input.value.trim();if(!content)return;button.disabled=true;const{error}=await supabaseClient.from('comments').insert([{post_id:postId,content,author_name:getUserName(currentUser),user_id:currentUser.id}]);button.disabled=false;if(error)return alert(error.message);input.value='';await loadComments(postId)}
function handleCommentKey(event,postId){if(event.key==='Enter'){event.preventDefault();createComment(postId)}}
document.addEventListener('click',e=>{const b=e.target.closest('.comment-button');if(b)createComment(b.dataset.postId)});

async function loadLikeCount(postId){if(!currentUser)return;const el=$(`like-count-${postId}`);if(!el)return;const{count}=await supabaseClient.from('likes').select('*',{count:'exact',head:true}).eq('post_id',postId);el.textContent=count||0}
async function likePost(postId){if(!currentUser)return;const button=$(`like-button-${postId}`);button.disabled=true;const{error}=await supabaseClient.from('likes').insert([{post_id:postId,user_id:currentUser.id}]);if(error&&error.code!=='23505'){button.disabled=false;return alert(error.message)}button.classList.add('liked');button.innerHTML=`♥ Liked <span id="like-count-${postId}"></span>`;await loadLikeCount(postId)}
async function checkIfLiked(postId){if(!currentUser)return;const button=$(`like-button-${postId}`);if(!button)return;const{data}=await supabaseClient.from('likes').select('id').eq('post_id',postId).eq('user_id',currentUser.id).maybeSingle();if(data){button.classList.add('liked');button.innerHTML=`♥ Liked <span id="like-count-${postId}"></span>`;button.disabled=true;await loadLikeCount(postId)}}
async function refreshLikeStates(){if(!currentUser)return;for(const button of document.querySelectorAll('.like-button')){const match=button.id.match(/^like-button-(.+)$/);if(match)await checkIfLiked(match[1])}}

async function openMemberProfile(userId,pushUrl=true){if(!currentUser)return;const modal=$('memberProfileModal'),body=$('memberProfileBody');modal.classList.add('open');body.innerHTML='<div class="muted">Loading member profile...</div>';const[{data:profile,error:pError},{data:posts,error:postError}]=await Promise.all([supabaseClient.from('profiles').select('id, full_name, bio, created_at').eq('id',userId).maybeSingle(),supabaseClient.from('posts').select('id, content, created_at').eq('user_id',userId).order('created_at',{ascending:false}).limit(5)]);if(pError||!profile){body.innerHTML='<div class="muted">This member profile is not available.</div>';return}const name=profile.full_name||'Community Member';body.innerHTML=`<div class="profile-hero"><div class="avatar">${escapeHtml(getInitials(name))}</div><div><div class="profile-name">${escapeHtml(name)}</div><div class="profile-bio">${escapeHtml(profile.bio||'No bio added yet.')}</div><div class="profile-meta">Member since ${formatMemberSince(profile.created_at)}</div></div></div><div class="section-title">Recent posts</div>${postError||!posts?.length?'<div class="muted">No recent posts.</div>':posts.map(p=>`<div class="mini-post"><div class="mini-post-content">${escapeHtml(p.content)}</div><div class="mini-post-date">${formatDate(p.created_at)}</div></div>`).join('')}`;if(pushUrl){const url=new URL(location.href);url.searchParams.set('member',userId);history.pushState({member:userId},'',url)}}
async function openRequestedMemberProfile(){if(!currentUser)return;const id=new URL(location.href).searchParams.get('member');if(id)await openMemberProfile(id,false)}
function closeMemberProfile(clearUrl=true){$('memberProfileModal').classList.remove('open');if(clearUrl){const url=new URL(location.href);url.searchParams.delete('member');history.pushState({},'',url)}}
window.addEventListener('popstate',()=>{const id=new URL(location.href).searchParams.get('member');if(id&&currentUser)openMemberProfile(id,false);else $('memberProfileModal').classList.remove('open')});

async function startApp(){await initializeAuth();if(currentUser){await loadPosts();await openRequestedMemberProfile()}else{clearMemberParam()}}
startApp();