const SUPABASE_URL='https://zbogfymmlnifzoasemlt.supabase.co';
const SUPABASE_KEY='sb_publishable_77b2DtF2XQLyfKEg7ZBNYA_odCDFWVJ';
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let currentUser=null,currentProfile=null,toastTimer=null,allPosts=[],commentsCache={},editTarget=null,reportTarget=null,notificationTimer=null;

const $=id=>document.getElementById(id);
const isAdmin=()=>currentProfile?.role==='admin';
function escapeHtml(text=''){const div=document.createElement('div');div.textContent=text;return div.innerHTML}
function getInitials(name=''){const p=name.trim().split(/\s+/).filter(Boolean);if(!p.length)return'?';return(p.length===1?p[0][0]:p[0][0]+p[p.length-1][0]).toUpperCase()}
function formatDate(value){return new Date(value).toLocaleString()}
function formatMemberSince(value){return new Date(value).toLocaleDateString(undefined,{month:'short',year:'numeric'})}
function setAuthMessage(message,isError=false){$('authMessage').textContent=message;$('authMessage').classList.toggle('error',isError)}
function setComposerMessage(message,isError=false){$('composerMessage').textContent=message;$('composerMessage').classList.toggle('error',isError)}
function showToast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600)}
function showLogin(){$('loginForm').style.display='block';$('signupForm').style.display='none';$('loginTab').classList.add('active');$('signupTab').classList.remove('active');setAuthMessage('')}
function showSignup(){$('loginForm').style.display='none';$('signupForm').style.display='block';$('loginTab').classList.remove('active');$('signupTab').classList.add('active');setAuthMessage('')}
function getUserName(user){if(!user)return'Community Member';if(currentProfile?.full_name)return currentProfile.full_name.trim();const m=user.user_metadata||{};return m.full_name||m.name||user.email?.split('@')[0]||'Community Member'}
function clearMemberParam(){const url=new URL(location.href);if(url.searchParams.has('member')){url.searchParams.delete('member');history.replaceState({},'',url)}}

async function signUp(){const name=$('signupName').value.trim(),email=$('signupEmail').value.trim(),password=$('signupPassword').value,button=$('signupButton');if(!name)return setAuthMessage('Please enter your full name.',true);if(!email)return setAuthMessage('Please enter your email address.',true);if(password.length<6)return setAuthMessage('Your password must be at least 6 characters.',true);button.disabled=true;button.textContent='Creating Account...';const{data,error}=await supabaseClient.auth.signUp({email,password,options:{data:{full_name:name}}});button.disabled=false;button.textContent='Create Account';if(error)return setAuthMessage(error.message,true);setAuthMessage(data.user&&!data.session?'Account created. Please check your email and confirm your address before signing in.':'Account created successfully.')}
async function signIn(){const email=$('loginEmail').value.trim(),password=$('loginPassword').value,button=$('loginButton');if(!email||!password)return setAuthMessage('Enter your email and password.',true);button.disabled=true;button.textContent='Signing In...';const{data,error}=await supabaseClient.auth.signInWithPassword({email,password});button.disabled=false;button.textContent='Sign In';if(error)return setAuthMessage(error.message,true);if(data.user)await handleUserSession(data.user)}
async function signOut(){if(currentUser)localStorage.removeItem(profileDraftKey(currentUser.id));clearInterval(notificationTimer);notificationTimer=null;const{error}=await supabaseClient.auth.signOut();if(error)return alert(error.message);currentUser=null;currentProfile=null;allPosts=[];commentsCache={};closeAllModals();clearMemberParam();updateAuthUI(null)}
async function loadCurrentProfile(user){currentProfile=null;if(!user)return;const{data,error}=await supabaseClient.from('profiles').select('id, full_name, bio, created_at, role, is_suspended').eq('id',user.id).maybeSingle();if(!error)currentProfile=data||null}
async function handleUserSession(user){currentUser=user;await loadCurrentProfile(user);updateAuthUI(user);if(currentProfile?.is_suspended)return;await loadPosts();await loadNotificationBadge();await openRequestedMemberProfile();startNotificationPolling()}
async function initializeAuth(){const{data}=await supabaseClient.auth.getSession();currentUser=data.session?.user||null;await loadCurrentProfile(currentUser);updateAuthUI(currentUser)}
supabaseClient.auth.onAuthStateChange(async(_,session)=>{currentUser=session?.user||null;await loadCurrentProfile(currentUser);updateAuthUI(currentUser);if(currentUser&&!currentProfile?.is_suspended){await loadPosts();await loadNotificationBadge();await openRequestedMemberProfile();startNotificationPolling()}else{clearInterval(notificationTimer);notificationTimer=null;clearMemberParam()}});

function updateAuthUI(user){const suspended=!!(user&&currentProfile?.is_suspended);$('guestShell').style.display=user?'none':'grid';$('suspendedShell').style.display=suspended?'block':'none';$('memberShell').style.display=user&&!suspended?'block':'none';$('memberHeaderActions').style.display=user?'flex':'none';if(user){const name=getUserName(user);$('accountName').textContent=name;$('accountAvatar').textContent=getInitials(name);$('composerAvatar').textContent=getInitials(name);$('memberWelcomeTitle').textContent=`Welcome back, ${name.split(' ')[0]}`;$('adminMenuItem').style.display=isAdmin()?'block':'none';}else{$('posts').innerHTML='';$('accountMenu').classList.remove('open')}}
function toggleAccountMenu(){$('accountMenu').classList.toggle('open')}
document.addEventListener('click',e=>{if(!e.target.closest('.account-wrap'))$('accountMenu')?.classList.remove('open')});
function closeAllModals(){document.querySelectorAll('.modal-backdrop').forEach(m=>m.classList.remove('open'))}

function profileDraftKey(id){return`nlc-profile-draft-${id}`}
function getProfileDraft(){if(!currentUser)return null;try{return JSON.parse(localStorage.getItem(profileDraftKey(currentUser.id))||'null')}catch{return null}}
function saveProfileDraft(){if(!currentUser)return;localStorage.setItem(profileDraftKey(currentUser.id),JSON.stringify({full_name:$('editProfileName').value,bio:$('editProfileBio').value}))}
function openMyProfile(){if(!currentUser)return;$('accountMenu').classList.remove('open');const draft=getProfileDraft();$('editProfileEmail').value=currentUser?.email||'';$('editProfileName').value=draft?.full_name??currentProfile?.full_name??getUserName(currentUser);$('editProfileBio').value=draft?.bio??currentProfile?.bio??'';$('editProfileMessage').textContent='';$('editProfileModal').classList.add('open')}
function closeMyProfile(){$('editProfileModal').classList.remove('open')}
async function saveProfile(){if(!currentUser)return;const name=$('editProfileName').value.trim(),bio=$('editProfileBio').value.trim(),button=$('saveProfileButton');if(!name){$('editProfileMessage').textContent='Please enter your full name.';return}button.disabled=true;button.textContent='Saving...';const{data,error}=await supabaseClient.from('profiles').update({full_name:name,bio:bio||null,updated_at:new Date().toISOString()}).eq('id',currentUser.id).select('id, full_name, bio, created_at, role, is_suspended').single();button.disabled=false;button.textContent='Save Changes';if(error){$('editProfileMessage').textContent=error.message;return}currentProfile=data;localStorage.removeItem(profileDraftKey(currentUser.id));updateAuthUI(currentUser);closeMyProfile();showToast('✓ Changes saved');await loadPosts()}

async function createPost(){if(!currentUser||currentProfile?.is_suspended)return;const textarea=$('postContent'),button=$('postButton'),content=textarea.value.trim();if(!content)return setComposerMessage('Write something first.',true);button.disabled=true;setComposerMessage('Posting...');const{error}=await supabaseClient.from('posts').insert([{content,author_name:getUserName(currentUser),user_id:currentUser.id}]);button.disabled=false;if(error)return setComposerMessage(error.message,true);textarea.value='';setComposerMessage('');showToast('Post published');await loadPosts()}

async function loadPosts(){if(!currentUser||currentProfile?.is_suspended){$('posts').innerHTML='';return}const container=$('posts');container.innerHTML='<div class="empty-state">Loading conversations...</div>';const{data,error}=await supabaseClient.from('posts').select('*').order('is_pinned',{ascending:false}).order('created_at',{ascending:false});if(error){container.innerHTML='<div class="empty-state">Unable to load posts.</div>';return}allPosts=data||[];if(!allPosts.length){container.innerHTML='<div class="empty-state">No posts yet. Start the first conversation.</div>';return}container.innerHTML=allPosts.map(renderPost).join('');for(const post of allPosts){loadLikeState(post.id);loadComments(post.id)}filterPosts()}
function authorButton(name,userId,cls='author-name-button'){return userId?`<button class="${cls}" type="button" onclick="openMemberProfile('${userId}')">${escapeHtml(name)}</button>`:`<span class="${cls.replace('-button','')}">${escapeHtml(name)}</span>`}
function ownerOrAdmin(userId){return currentUser&&(currentUser.id===userId||isAdmin())}
function renderPost(post){const name=post.author_name||'Community Member',initials=getInitials(name),canManage=ownerOrAdmin(post.user_id);const pin=post.is_pinned?'<span class="pinned-badge">📌 Pinned</span>':'';const edited=post.edited_at?' · edited':'';return`<article class="post" id="post-${post.id}" data-search="${escapeHtml((name+' '+post.content).toLowerCase())}"><div class="post-top"><div class="post-author"><div class="avatar">${escapeHtml(initials)}</div><div class="author-meta">${authorButton(name,post.user_id)}<div class="post-date">${formatDate(post.created_at)}${edited}</div></div></div><div class="post-tools">${pin}${isAdmin()?`<button class="tool-button" type="button" onclick="togglePin('${post.id}',${post.is_pinned})">${post.is_pinned?'Unpin':'Pin'}</button>`:''}${canManage?`<button class="tool-button" type="button" onclick="startEdit('post','${post.id}')">Edit</button><button class="tool-button danger-text" type="button" onclick="deleteContent('post','${post.id}')">Delete</button>`:`<button class="tool-button" type="button" onclick="openReport('post','${post.id}')">Report</button>`}</div></div><div class="post-content">${escapeHtml(post.content)}</div><div class="post-actions"><button class="action-button like-button" id="like-button-${post.id}" type="button" onclick="toggleLike('${post.id}')">♡ Like <span id="like-count-${post.id}">0</span></button></div><div class="comments"><div class="comments-title" id="comments-title-${post.id}">Comments</div><div id="comments-${post.id}">Loading comments...</div><div class="comment-box"><input id="comment-${post.id}" maxlength="500" placeholder="Write a comment..." onkeydown="handleCommentKey(event,'${post.id}')"><button class="primary comment-button" data-post-id="${post.id}" type="button">Comment</button></div></div></article>`}
function filterPosts(){const q=($('feedSearch')?.value||'').trim().toLowerCase();let visible=0;document.querySelectorAll('.post').forEach(post=>{const match=!q||post.dataset.search.includes(q);post.style.display=match?'block':'none';if(match)visible++});if($('feedLabel'))$('feedLabel').textContent=q?`${visible} result${visible===1?'':'s'}`:'Latest conversations'}

async function loadComments(postId){if(!currentUser)return;const box=$(`comments-${postId}`);if(!box)return;const{data,error}=await supabaseClient.from('comments').select('*').eq('post_id',postId).order('created_at',{ascending:true});if(error){box.innerHTML='<div class="muted">Unable to load comments.</div>';return}commentsCache[postId]=data||[];const count=data?.length||0;$(`comments-title-${postId}`).textContent=`💬 ${count} Comment${count===1?'':'s'}`;if(!count){box.innerHTML='<div class="muted">No comments yet.</div>';return}box.innerHTML=data.map(c=>{const name=c.author_name||'Community Member',canManage=ownerOrAdmin(c.user_id),edited=c.edited_at?' · edited':'';return`<div class="comment" id="comment-row-${c.id}"><div class="comment-head"><div class="comment-person"><div class="avatar">${escapeHtml(getInitials(name))}</div>${authorButton(name,c.user_id,'author-name-button comment-author')}</div><div class="comment-tools">${canManage?`<button class="tiny-button" type="button" onclick="startEdit('comment','${c.id}','${postId}')">Edit</button><button class="tiny-button danger-text" type="button" onclick="deleteContent('comment','${c.id}','${postId}')">Delete</button>`:`<button class="tiny-button" type="button" onclick="openReport('comment','${c.id}')">Report</button>`}</div></div><div class="comment-content">${escapeHtml(c.content)}</div><div class="comment-date">${formatDate(c.created_at)}${edited}</div></div>`}).join('')}
async function createComment(postId){if(!currentUser)return;const input=$(`comment-${postId}`),button=document.querySelector(`[data-post-id="${postId}"]`),content=input.value.trim();if(!content)return;button.disabled=true;const{error}=await supabaseClient.from('comments').insert([{post_id:postId,content,author_name:getUserName(currentUser),user_id:currentUser.id}]);button.disabled=false;if(error)return alert(error.message);input.value='';await loadComments(postId);showToast('Comment added')}
function handleCommentKey(event,postId){if(event.key==='Enter'){event.preventDefault();createComment(postId)}}
document.addEventListener('click',e=>{const b=e.target.closest('.comment-button');if(b)createComment(b.dataset.postId)});

async function loadLikeState(postId){if(!currentUser)return;const[countResult,likedResult]=await Promise.all([supabaseClient.from('likes').select('*',{count:'exact',head:true}).eq('post_id',postId),supabaseClient.from('likes').select('id').eq('post_id',postId).eq('user_id',currentUser.id).maybeSingle()]);const button=$(`like-button-${postId}`),countEl=$(`like-count-${postId}`);if(!button||!countEl)return;countEl.textContent=countResult.count||0;const liked=!!likedResult.data;button.classList.toggle('liked',liked);button.childNodes[0].nodeValue=liked?'♥ Liked ':'♡ Like ';button.disabled=false}
async function toggleLike(postId){if(!currentUser)return;const button=$(`like-button-${postId}`);button.disabled=true;const{data}=await supabaseClient.from('likes').select('id').eq('post_id',postId).eq('user_id',currentUser.id).maybeSingle();let error;if(data){({error}=await supabaseClient.from('likes').delete().eq('id',data.id))}else{({error}=await supabaseClient.from('likes').insert([{post_id:postId,user_id:currentUser.id}]))}if(error){button.disabled=false;return alert(error.message)}await loadLikeState(postId)}

function startEdit(type,id,postId=null){editTarget={type,id,postId};let content='';if(type==='post')content=allPosts.find(p=>p.id===id)?.content||'';else content=(commentsCache[postId]||[]).find(c=>c.id===id)?.content||'';$('editContentTitle').textContent=type==='post'?'Edit Post':'Edit Comment';$('editContentText').maxLength=type==='post'?3000:500;$('editContentText').value=content;$('editContentMessage').textContent='';$('editContentModal').classList.add('open')}
function closeEditContent(){$('editContentModal').classList.remove('open');editTarget=null}
async function saveEditedContent(){if(!editTarget)return;const content=$('editContentText').value.trim();if(!content){$('editContentMessage').textContent='Content cannot be empty.';return}const table=editTarget.type==='post'?'posts':'comments';const{error}=await supabaseClient.from(table).update({content,edited_at:new Date().toISOString()}).eq('id',editTarget.id);if(error){$('editContentMessage').textContent=error.message;return}const postId=editTarget.postId;closeEditContent();showToast('Changes saved');if(table==='posts')await loadPosts();else await loadComments(postId)}
async function deleteContent(type,id,postId=null){const label=type==='post'?'post':'comment';if(!confirm(`Delete this ${label}? This cannot be undone.`))return;const table=type==='post'?'posts':'comments';const{error}=await supabaseClient.from(table).delete().eq('id',id);if(error)return alert(error.message);showToast(`${label[0].toUpperCase()+label.slice(1)} deleted`);if(type==='post')await loadPosts();else await loadComments(postId)}
async function togglePin(postId,isPinned){if(!isAdmin())return;const{error}=await supabaseClient.from('posts').update({is_pinned:!isPinned}).eq('id',postId);if(error)return alert(error.message);showToast(isPinned?'Post unpinned':'Post pinned');await loadPosts()}

function openReport(type,id){reportTarget={type,id};$('reportReason').value='';$('reportMessage').textContent='';$('reportModal').classList.add('open')}
function closeReport(){$('reportModal').classList.remove('open');reportTarget=null}
async function submitReport(){if(!reportTarget)return;const reason=$('reportReason').value.trim();if(reason.length<3){$('reportMessage').textContent='Please add a brief reason.';return}const{error}=await supabaseClient.from('reports').insert([{reporter_id:currentUser.id,target_type:reportTarget.type,target_id:reportTarget.id,reason}]);if(error){$('reportMessage').textContent=error.code==='23505'?'You already reported this content.':error.message;return}closeReport();showToast('Report sent privately to admin')}

function openRules(){$('accountMenu').classList.remove('open');$('rulesModal').classList.add('open')}
function closeRules(){$('rulesModal').classList.remove('open')}

function startNotificationPolling(){clearInterval(notificationTimer);notificationTimer=setInterval(()=>{if(currentUser&&!currentProfile?.is_suspended)loadNotificationBadge()},60000)}
async function loadNotificationBadge(){if(!currentUser)return;const{count}=await supabaseClient.from('notifications').select('*',{count:'exact',head:true}).is('read_at',null);const n=count||0;$('notificationBadge').textContent=n>99?'99+':n;$('notificationBadge').style.display=n?'grid':'none'}
async function openNotifications(){$('notificationsModal').classList.add('open');await loadNotifications()}
function closeNotifications(){$('notificationsModal').classList.remove('open')}
async function loadNotifications(){const body=$('notificationsBody');body.innerHTML='<div class="muted">Loading notifications...</div>';const{data,error}=await supabaseClient.from('notifications').select('*').order('created_at',{ascending:false}).limit(40);if(error){body.innerHTML='<div class="muted">Unable to load notifications.</div>';return}if(!data?.length){body.innerHTML='<div class="empty-state flat">No notifications yet.</div>';return}const ids=[...new Set(data.map(n=>n.actor_id).filter(Boolean))];let profiles=[];if(ids.length){const r=await supabaseClient.from('profiles').select('id,full_name').in('id',ids);profiles=r.data||[]}const names=Object.fromEntries(profiles.map(p=>[p.id,p.full_name||'A member']));body.innerHTML=data.map(n=>{const actor=escapeHtml(names[n.actor_id]||'A member'),text=n.type==='comment'?`${actor} commented on your post.`:`${actor} liked your post.`;return`<button class="notification-item ${n.read_at?'':'unread'}" type="button" onclick="openNotificationPost('${n.id}','${n.post_id||''}')"><span>${n.type==='comment'?'💬':'♥'}</span><span><strong>${text}</strong><small>${formatDate(n.created_at)}</small></span></button>`}).join('')}
async function openNotificationPost(notificationId,postId){await supabaseClient.from('notifications').update({read_at:new Date().toISOString()}).eq('id',notificationId);await loadNotificationBadge();closeNotifications();const el=$(`post-${postId}`);if(el){el.scrollIntoView({behavior:'smooth',block:'center'});el.classList.add('highlight');setTimeout(()=>el.classList.remove('highlight'),1800)}}
async function markAllNotificationsRead(){await supabaseClient.from('notifications').update({read_at:new Date().toISOString()}).is('read_at',null);await loadNotificationBadge();await loadNotifications()}

async function openMemberProfile(userId,pushUrl=true){if(!currentUser)return;const modal=$('memberProfileModal'),body=$('memberProfileBody');modal.classList.add('open');body.innerHTML='<div class="muted">Loading member profile...</div>';const[{data:profile,error:pError},{data:posts,error:postError}]=await Promise.all([supabaseClient.from('profiles').select('id, full_name, bio, created_at, role').eq('id',userId).maybeSingle(),supabaseClient.from('posts').select('id, content, created_at').eq('user_id',userId).order('created_at',{ascending:false}).limit(5)]);if(pError||!profile){body.innerHTML='<div class="muted">This member profile is not available.</div>';return}const name=profile.full_name||'Community Member',role=profile.role==='admin'?'<span class="role-badge">Admin</span>':'';body.innerHTML=`<div class="profile-hero"><div class="avatar">${escapeHtml(getInitials(name))}</div><div><div class="profile-name">${escapeHtml(name)} ${role}</div><div class="profile-bio">${escapeHtml(profile.bio||'No bio added yet.')}</div><div class="profile-meta">Member since ${formatMemberSince(profile.created_at)}</div></div></div><div class="section-title">Recent posts</div>${postError||!posts?.length?'<div class="muted">No recent posts.</div>':posts.map(p=>`<div class="mini-post"><div class="mini-post-content">${escapeHtml(p.content)}</div><div class="mini-post-date">${formatDate(p.created_at)}</div></div>`).join('')}`;if(pushUrl){const url=new URL(location.href);url.searchParams.set('member',userId);history.pushState({member:userId},'',url)}}
async function openRequestedMemberProfile(){if(!currentUser||currentProfile?.is_suspended)return;const id=new URL(location.href).searchParams.get('member');if(id)await openMemberProfile(id,false)}
function closeMemberProfile(clearUrl=true){$('memberProfileModal').classList.remove('open');if(clearUrl){const url=new URL(location.href);url.searchParams.delete('member');history.pushState({},'',url)}}
window.addEventListener('popstate',()=>{const id=new URL(location.href).searchParams.get('member');if(id&&currentUser&&!currentProfile?.is_suspended)openMemberProfile(id,false);else $('memberProfileModal').classList.remove('open')});

async function openAdminPanel(){if(!isAdmin())return;$('accountMenu').classList.remove('open');$('adminModal').classList.add('open');await loadAdminStats();await showAdminTab('reports')}
function closeAdminPanel(){$('adminModal').classList.remove('open')}
async function loadAdminStats(){const[members,posts,reports]=await Promise.all([supabaseClient.from('profiles').select('*',{count:'exact',head:true}),supabaseClient.from('posts').select('*',{count:'exact',head:true}),supabaseClient.from('reports').select('*',{count:'exact',head:true}).eq('status','open')]);$('adminStats').innerHTML=`<div><strong>${members.count||0}</strong><span>Members</span></div><div><strong>${posts.count||0}</strong><span>Posts</span></div><div><strong>${reports.count||0}</strong><span>Open reports</span></div>`}
async function showAdminTab(tab){$('reportsTab').classList.toggle('active',tab==='reports');$('membersTab').classList.toggle('active',tab==='members');$('adminReports').style.display=tab==='reports'?'block':'none';$('adminMembers').style.display=tab==='members'?'block':'none';if(tab==='reports')await loadAdminReports();else await loadAdminMembers()}
async function loadAdminReports(){const box=$('adminReports');box.innerHTML='<div class="muted">Loading reports...</div>';const{data,error}=await supabaseClient.from('reports').select('*').order('created_at',{ascending:false});if(error){box.innerHTML='<div class="muted">Unable to load reports.</div>';return}const open=(data||[]).filter(r=>r.status==='open');if(!open.length){box.innerHTML='<div class="empty-state flat">No open reports. Community is clear.</div>';return}let html='';for(const r of open){let targetText='Content unavailable';const table=r.target_type==='post'?'posts':'comments';const{data:target}=await supabaseClient.from(table).select('content,author_name').eq('id',r.target_id).maybeSingle();if(target)targetText=`${target.author_name||'Member'}: ${target.content}`;html+=`<div class="report-card"><div class="report-meta">${escapeHtml(r.target_type)} · ${formatDate(r.created_at)}</div><div class="report-target">${escapeHtml(targetText)}</div><div class="report-reason"><strong>Reason:</strong> ${escapeHtml(r.reason)}</div><div class="report-actions"><button class="secondary" type="button" onclick="resolveReport('${r.id}','dismissed')">Dismiss</button>${target?`<button class="primary danger-soft" type="button" onclick="adminRemoveReported('${r.id}','${r.target_type}','${r.target_id}')">Remove content</button>`:''}</div></div>`}box.innerHTML=html}
async function resolveReport(id,status){const{error}=await supabaseClient.from('reports').update({status,resolved_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);await loadAdminStats();await loadAdminReports()}
async function adminRemoveReported(reportId,type,targetId){if(!confirm('Remove this reported content from the community?'))return;const table=type==='post'?'posts':'comments';const{error}=await supabaseClient.from(table).delete().eq('id',targetId);if(error)return alert(error.message);await supabaseClient.from('reports').update({status:'actioned',resolved_at:new Date().toISOString()}).eq('id',reportId);showToast('Reported content removed');await loadPosts();await loadAdminStats();await loadAdminReports()}
async function loadAdminMembers(){const box=$('adminMembers');box.innerHTML='<div class="muted">Loading members...</div>';const{data,error}=await supabaseClient.from('profiles').select('id,full_name,bio,role,is_suspended,created_at').order('created_at',{ascending:true});if(error){box.innerHTML='<div class="muted">Unable to load members.</div>';return}box.innerHTML=(data||[]).map(p=>`<div class="member-row"><div><strong>${escapeHtml(p.full_name||'Community Member')}</strong>${p.role==='admin'?'<span class="role-badge">Admin</span>':''}<small>Joined ${formatMemberSince(p.created_at)}</small></div><div>${p.id===currentUser.id?'<span class="muted">You</span>':`<button class="${p.is_suspended?'secondary':'danger-button'}" type="button" onclick="setMemberSuspension('${p.id}',${!p.is_suspended})">${p.is_suspended?'Restore access':'Suspend'}</button>`}</div></div>`).join('')}
async function setMemberSuspension(memberId,suspend){if(!isAdmin()||memberId===currentUser.id)return;if(suspend&&!confirm('Suspend this member? They will lose access to community content and participation.'))return;const{error}=await supabaseClient.from('profiles').update({is_suspended:suspend,updated_at:new Date().toISOString()}).eq('id',memberId);if(error)return alert(error.message);showToast(suspend?'Member suspended':'Member access restored');await loadAdminMembers()}

async function startApp(){await initializeAuth();if(currentUser&&!currentProfile?.is_suspended){await loadPosts();await loadNotificationBadge();await openRequestedMemberProfile();startNotificationPolling()}else if(!currentUser){clearMemberParam()}}
startApp();